image: fudanchii/base
script:
  - echo test
  - sleep 3
  - echo yay
  - sleep 3
  - test -d /tmp && echo '/tmp exists'
  - sleep 3
  - test -d /srv && echo '/srv exists'
  - sleep 3
  - echo finished.
  - cat $0
notify:
  email:
    recipients:
      - nurahmadie@gmail.com
