image: fudanchii/base
script:
  - git --version
  - echo test
  - sleep 3
  - test -d /tmp && echo '/tmp exists'
  - sleep 3
  - test -d /srv && echo '/srv exists'
  - sleep 3
  - echo finished.
  - cat $0
notify:
  email:
    recipients:
      - nurahmadie@gmail.com
deploy:
  ssh:
    target: {{ssh_host}} {{ssh_port}}
    branch: master
    cmd: sar
